# Generated by Django 4.2.5 on 2023-09-30 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardDisplay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('award_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('competition_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CompositePhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_video_path', models.CharField(max_length=255)),
                ('template_html_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentDisplay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LabEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('event', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LabMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('introduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media_link', models.URLField()),
                ('media_type', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('meeting_link', models.URLField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TemplateHTML',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.visitrecord')),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.labmember')),
            ],
        ),
    ]
