# Generated by Django 4.2.5 on 2023-09-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '資料庫',
                'verbose_name_plural': '資料庫',
            },
        ),
        migrations.AlterModelOptions(
            name='awarddisplay',
            options={'verbose_name': '獎狀展示', 'verbose_name_plural': '獎狀展示'},
        ),
        migrations.AlterModelOptions(
            name='competitionrecord',
            options={'verbose_name': '競賽紀錄', 'verbose_name_plural': '競賽紀錄'},
        ),
        migrations.AlterModelOptions(
            name='compositephoto',
            options={'verbose_name': '合成照片', 'verbose_name_plural': '合成照片'},
        ),
        migrations.AlterModelOptions(
            name='equipmentdisplay',
            options={'verbose_name': '設備展示', 'verbose_name_plural': '設備展示'},
        ),
        migrations.AlterModelOptions(
            name='eventparticipant',
            options={'verbose_name': '活動參與人員', 'verbose_name_plural': '活動參與人員'},
        ),
        migrations.AlterModelOptions(
            name='labevent',
            options={'verbose_name': '實驗室事件', 'verbose_name_plural': '實驗室事件'},
        ),
        migrations.AlterModelOptions(
            name='labmember',
            options={'verbose_name': '實驗室成員介紹', 'verbose_name_plural': '實驗室成員介紹'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': '多媒體', 'verbose_name_plural': '多媒體'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': '會議', 'verbose_name_plural': '會議'},
        ),
        migrations.AlterModelOptions(
            name='templatehtml',
            options={'verbose_name': '範本html', 'verbose_name_plural': '範本html'},
        ),
        migrations.AlterModelOptions(
            name='visitrecord',
            options={'verbose_name': '參訪紀錄', 'verbose_name_plural': '參訪紀錄'},
        ),
        migrations.AddField(
            model_name='labmember',
            name='student_level',
            field=models.IntegerField(choices=[(1, '大學部'), (2, '研究生'), (3, '博士後'), (4, '研究助理'), (5, '教授')], default=1),
        ),
        migrations.AlterField(
            model_name='compositephoto',
            name='photo_video_path',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='compositephoto',
            name='template_html_path',
            field=models.FileField(blank=True, null=True, upload_to='templates/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='path',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='templatehtml',
            name='template_path',
            field=models.FileField(blank=True, null=True, upload_to='templates/'),
        ),
    ]
