# Generated by Django 4.2.5 on 2023-09-30 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('database', '0004_delete_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compositephoto',
            name='template_html_path',
        ),
        migrations.AddField(
            model_name='compositephoto',
            name='template_html',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.templatehtml', verbose_name='模板 HTML'),
        ),
        migrations.AddField(
            model_name='labevent',
            name='content',
            field=models.TextField(null=True, verbose_name='介紹內容'),
        ),
        migrations.AlterField(
            model_name='awarddisplay',
            name='award_name',
            field=models.CharField(max_length=255, verbose_name='獎項名稱'),
        ),
        migrations.AlterField(
            model_name='awarddisplay',
            name='content',
            field=models.TextField(null=True, verbose_name='介紹內容'),
        ),
        migrations.AlterField(
            model_name='awarddisplay',
            name='date',
            field=models.DateField(null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='awarddisplay',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='編號'),
        ),
        migrations.AlterField(
            model_name='competitionrecord',
            name='competition_name',
            field=models.CharField(max_length=255, verbose_name='競賽名稱'),
        ),
        migrations.AlterField(
            model_name='competitionrecord',
            name='content',
            field=models.TextField(null=True, verbose_name='介紹內容'),
        ),
        migrations.AlterField(
            model_name='competitionrecord',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='competitionrecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='編號'),
        ),
        migrations.AlterField(
            model_name='compositephoto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='編號'),
        ),
        migrations.AlterField(
            model_name='compositephoto',
            name='photo_video_path',
            field=models.ImageField(blank=True, null=True, upload_to='media/videos/', verbose_name='照片/影片路徑'),
        ),
        migrations.AlterField(
            model_name='equipmentdisplay',
            name='content',
            field=models.TextField(null=True, verbose_name='介紹內容'),
        ),
        migrations.AlterField(
            model_name='equipmentdisplay',
            name='equipment_name',
            field=models.CharField(max_length=255, verbose_name='設備名稱'),
        ),
        migrations.AlterField(
            model_name='equipmentdisplay',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='編號'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='內容類型'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='編號'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='物件 ID'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='participant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.labmember', verbose_name='參與者 ID'),
        ),
        migrations.AlterField(
            model_name='labevent',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='labevent',
            name='event',
            field=models.TextField(null=True, verbose_name='事件'),
        ),
        migrations.AlterField(
            model_name='labevent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='編號'),
        ),
        migrations.AlterField(
            model_name='labevent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='標題'),
        ),
        migrations.AlterField(
            model_name='labmember',
            name='department',
            field=models.CharField(max_length=255, verbose_name='系所'),
        ),
        migrations.AlterField(
            model_name='labmember',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='編號'),
        ),
        migrations.AlterField(
            model_name='labmember',
            name='introduction',
            field=models.TextField(null=True, verbose_name='介紹'),
        ),
        migrations.AlterField(
            model_name='labmember',
            name='name',
            field=models.CharField(max_length=255, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='labmember',
            name='position',
            field=models.CharField(max_length=255, verbose_name='職位'),
        ),
        migrations.AlterField(
            model_name='labmember',
            name='student_id',
            field=models.CharField(max_length=10, verbose_name='學號'),
        ),
        migrations.AlterField(
            model_name='labmember',
            name='student_level',
            field=models.IntegerField(choices=[(1, '大學部'), (2, '研究生'), (3, '博士後'), (4, '研究助理'), (5, '教授')], default=1, verbose_name='學級'),
        ),
        migrations.AlterField(
            model_name='media',
            name='content',
            field=models.TextField(verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='media',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='內容類型'),
        ),
        migrations.AlterField(
            model_name='media',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='編號'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', '圖片'), ('video', '影片')], max_length=255, verbose_name='多媒體類型'),
        ),
        migrations.AlterField(
            model_name='media',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='物件 ID'),
        ),
        migrations.AlterField(
            model_name='media',
            name='path',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='路徑'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='content',
            field=models.TextField(null=True, verbose_name='會議內容'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='編號'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_link',
            field=models.URLField(null=True, verbose_name='會議連結'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(max_length=255, verbose_name='會議名稱'),
        ),
        migrations.AlterField(
            model_name='templatehtml',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='編號'),
        ),
        migrations.AlterField(
            model_name='templatehtml',
            name='template_path',
            field=models.FileField(blank=True, null=True, upload_to='templates/', verbose_name='模板路徑'),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='content',
            field=models.TextField(null=True, verbose_name='介紹內容'),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='date',
            field=models.DateField(null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='event_name',
            field=models.CharField(max_length=255, verbose_name='活動名稱'),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='編號'),
        ),
    ]
