# Generated by Django 4.2.5 on 2023-09-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_compositephoto_template_html_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositephoto',
            name='content_a',
            field=models.TextField(null=True, verbose_name='內容區域A'),
        ),
        migrations.AddField(
            model_name='compositephoto',
            name='content_b',
            field=models.TextField(null=True, verbose_name='內容區域B'),
        ),
        migrations.AddField(
            model_name='compositephoto',
            name='content_c',
            field=models.TextField(null=True, verbose_name='內容區域C'),
        ),
        migrations.AddField(
            model_name='compositephoto',
            name='content_d',
            field=models.TextField(null=True, verbose_name='內容區域D'),
        ),
        migrations.AddField(
            model_name='compositephoto',
            name='content_event',
            field=models.TextField(null=True, verbose_name='事件'),
        ),
        migrations.AddField(
            model_name='compositephoto',
            name='content_title',
            field=models.TextField(null=True, verbose_name='主題'),
        ),
    ]
