# Generated by Django 4.2.5 on 2023-09-30 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_compositephoto_photo_video_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compositephoto',
            name='photo_video_path',
        ),
    ]
