# Generated by Django 4.2.5 on 2023-10-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_remove_compositephoto_photo_video_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='path',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='路徑'),
        ),
        migrations.AlterField(
            model_name='templatehtml',
            name='template_path',
            field=models.FileField(blank=True, null=True, upload_to='templates/', verbose_name='模板路徑'),
        ),
    ]
